### PR TITLE
Backpack version 6

### PR DESCRIPTION
**Pull request by malek77z**
Added some tweaks to enable backpack version 6

### CODE REVIEW

**Review by ziming — APPROVED** [review]
hmm okay i just merge and test against the main branch 1st before i tag a new release

**Comment by malek77z** [comment]
Just deployed with your dev-main and working as expected.

**Comment by ziming** [comment]
Hmm okay i will tag a new release. My own upgrade to backpack 6 got some errors on the index pages though. Not sure why

https://github.com/Laravel-Backpack/CRUD/issues/5184

**Comment by malek77z** [comment]
oh, im on tabler, so it might be different

**Comment by malek77z** [comment]
i think you are having an issue with basset reading through more

**Pull request merged**
